-- Fuel Control schema. Run once in the Supabase SQL editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', email text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.vehicles (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  name text not null, brand text not null default '', model text not null default '', plate_number text not null default '',
  fuel_type text not null default '', summer_norm numeric(10,2) not null check(summer_norm >= 0),
  winter_norm numeric(10,2) not null check(winter_norm >= 0), is_active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, name)
);
create table if not exists public.fuel_records (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade, start_date date not null, end_date date not null,
  start_odometer numeric not null, end_odometer numeric not null, distance_km numeric not null,
  start_fuel numeric not null, refueled_fuel numeric not null, season text not null check(season in ('summer','winter')),
  used_norm numeric(10,2) not null, normative_consumption numeric not null, calculated_balance numeric not null,
  actual_end_fuel numeric, difference numeric, note text not null default '', created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(), check(end_date >= start_date), check(end_odometer >= start_odometer)
);
create index if not exists vehicles_user_id_idx on public.vehicles(user_id);
create index if not exists fuel_records_user_id_idx on public.fuel_records(user_id);
create index if not exists fuel_records_vehicle_id_idx on public.fuel_records(vehicle_id);

create or replace function public.is_admin() returns boolean language sql stable security definer
set search_path = public as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin' and is_active); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer
set search_path = public as $$ begin insert into profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
create or replace function public.protect_profile_fields() returns trigger language plpgsql security definer
set search_path = public as $$ begin if not public.is_admin() then new.id=old.id; new.email=old.email; new.role=old.role; new.is_active=old.is_active; end if; return new; end; $$;
drop trigger if exists profiles_protect_fields on profiles; create trigger profiles_protect_fields before update on profiles for each row execute procedure public.protect_profile_fields();
drop trigger if exists profiles_updated_at on profiles; create trigger profiles_updated_at before update on profiles for each row execute procedure public.set_updated_at();
drop trigger if exists vehicles_updated_at on vehicles; create trigger vehicles_updated_at before update on vehicles for each row execute procedure public.set_updated_at();
drop trigger if exists fuel_records_updated_at on fuel_records; create trigger fuel_records_updated_at before update on fuel_records for each row execute procedure public.set_updated_at();

alter table profiles enable row level security; alter table vehicles enable row level security; alter table fuel_records enable row level security;
create policy "profiles read own or admin" on profiles for select using(id=auth.uid() or public.is_admin());
create policy "profiles update own or admin" on profiles for update using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy "vehicles read own or admin" on vehicles for select using(user_id=auth.uid() or public.is_admin());
create policy "vehicles insert own" on vehicles for insert with check(user_id=auth.uid());
create policy "vehicles update own" on vehicles for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "vehicles delete own" on vehicles for delete using(user_id=auth.uid());
create policy "records read own or admin" on fuel_records for select using(user_id=auth.uid() or public.is_admin());
create policy "records insert own" on fuel_records for insert with check(user_id=auth.uid() and exists(select 1 from vehicles v where v.id=vehicle_id and v.user_id=auth.uid()));
create policy "records update own" on fuel_records for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "records delete own" on fuel_records for delete using(user_id=auth.uid());
