-- Run in the Supabase SQL editor. All access is restricted to auth.uid().
create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  brand text not null default '', model text not null default '',
  plate_number text not null default '', fuel_type text not null default '',
  summer_norm double precision not null check (summer_norm >= 0),
  winter_norm double precision not null check (winter_norm >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  start_date date not null, end_date date not null,
  start_odometer double precision not null, end_odometer double precision not null,
  distance_km double precision not null, start_fuel double precision not null,
  refueled_fuel double precision not null,
  season text not null check (season in ('summer', 'winter')),
  used_norm double precision not null, normative_consumption double precision not null,
  calculated_balance double precision not null, actual_end_fuel double precision,
  difference double precision, note text not null default '',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.vehicles enable row level security;
alter table public.records enable row level security;

create policy "owners manage vehicles" on public.vehicles
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "owners manage records" on public.records
  for all using (auth.uid() = user_id) with check (
    auth.uid() = user_id and exists (
      select 1 from public.vehicles v
      where v.id = vehicle_id and v.user_id = auth.uid()
    )
  );
